import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core";
import "@copilotkit/react-ui/v2/styles.css";
import { cn } from "@/lib/utils";
import { UserProvider } from "./_lib/UserContext";
import Link from "next/link";
import Header from "@/components/header";

const geistHeading = Geist({ subsets: ["latin"], variable: "--font-heading" });

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cookster - AI-Powered Recipe Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        geistHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col relative">
        <CopilotKit
          runtimeUrl="/api/copilotkit"
          publicApiKey="ck_pub_0de59986ce5a6f0af5fbb1a2841a4b56"
          publicLicenseKey="ck_pub_0de59986ce5a6f0af5fbb1a2841a4b56"
        >
          <UserProvider>
            <Header />
             {children}
              </UserProvider>
        </CopilotKit>
      </body>
    </html>
  );
}
              