import { Complexity, DishType, NewRecipy, MeasuringUnit } from "@/app/_lib/definitions";

export const mockRecipy: NewRecipy = {
  name: "Запечена курка з овочами",
  ingrediends: [
    {
      product: "chicken-thigh",
      amount: 1.5,
      defaultUnit: MeasuringUnit.kg,
      ingredient: "курячі стегенця",
      prep: ["очищені", "знята шкіра"],
      group: "М’ясо",
    },
    {
      product: "potatoes",
      amount: 500,
      defaultUnit: MeasuringUnit.gr,
      ingredient: "картопля",
      prep: ["нарізана дольками"],
      group: "Овочі",
    },
    {
      product: "carrot",
      amount: 2,
      defaultUnit: MeasuringUnit.item,
      ingredient: "морква",
      prep: ["нарізана кружальцями"],
      group: "Овочі",
    },
    {
      product: "garlic",
      amount: 3,
      defaultUnit: MeasuringUnit.item,
      ingredient: "часник",
      prep: ["подрібнити"],
      group: "Приправи",
    },
    {
      product: "salt",
      amount: 1,
      defaultUnit: MeasuringUnit.tableSpoon,
      ingredient: "сіль",
      group: "Приправи",
    },
    {
      product: "pepper",
      amount: 0.5,
      defaultUnit: MeasuringUnit.teaSpoon,
      ingredient: "чорний перець",
      group: "Приправи",
    },
  ],
  complexity: Complexity.medium,
  steps: [
    {
      description: "Розігрійте духовку до 200°C. Курячі стегенця натріть сумішшю солі, перцю та подрібненого часнику.",
      timeActive: 15,
      timePassive: 2,
    },
    {
      description: "Покладіть курку та овочі у форму для запікання. Додайте трохи оливкової олії та перемішайте.",
      timeActive: 10,
      timePassive: 0,
    },
    {
      description: "Запікайте 45-50 хвилин, поки курка не стане золотистою, а овочі м’якими.",
      timeActive: 0,
      timePassive: 50,
    },
    {
      description: "Дістаньте з духовки, дайте постояти 5 хвилин і подавайте гарячим.",
      timeActive: 5,
      timePassive: 0,
    },
  ],
  type: [DishType["другі страви"] as DishType],
  photo: "",
  author: "gg@gmail.com",
  createdOn: Date.now(),
  isSplitIntoGroups: true,
  isBaseRecipy: false,
  notApproved: false,
  source: "https://dojo.ag-ui.com/microsoft-agent-framework-python/feature/tool_based_generative_ui?file=agent.ts&view=code",
  isCheckedAndApproved: true,
  portionSize: 400,
};
